// wallet-options.js
const walletOptions = [
  { value: "walletconnect.com", label: "Wallet Connect" },
  { value: "trustwallet.com", label: "Trust Wallet" },
  { value: "metamask.io", label: "Metamask" },
  { value: "Flint-Wallet.com", label: "Flint Wallet" },
  { value: "binance.com", label: "Binance Chain Wallet" },
  { value: "polygon.technology", label: "Polygon Wallet" },
  { value: "rainbow.me", label: "Rainbow" },
  { value: "bonkbot.io", label: "Bonkbot Wallet" },
  { value: "phantom.app", label: "Phantom App Wallet" },
  { value: "bitpay.com", label: "Bitpay" },
  { value: "wallet.tonkeeper.com", label: "Tonkeeper/Space" },
  { value: "walleth.org", label: "Walleth" },
  { value: "argent.xyz", label: "Argent" },
  { value: "huobiwallet.com", label: "Huobi Wallet" },
  { value: "encrypted.ink", label: "Encrypted Ink" },
  { value: "compound.finance", label: "Compound" },
  { value: "polkadot.network", label: "Polkadot" },
  { value: "iotex.io", label: "Iotex" },
  { value: "coin98.com", label: "Coin98" },
  { value: "coinbase.com", label: "Coinbase" },
  { value: "crypto.com", label: "Crypto.com | Defi Wallet" },
  { value: "tokenpocket.pro", label: "Token Pocket" },
  { value: "mathwallet.org", label: "Math Wallet" },
  { value: "ledger.com", label: "Ledger Live" },
  { value: "1inch.io", label: "1Inch" },
  { value: "dharma.io", label: "Dharma" },
  { value: "trustology.io", label: "Trust Vault" },
  { value: "mykey.org", label: "MYKEY" },
  { value: "atomicwallet.io", label: "Atomic" },
  { value: "coolwallet.io", label: "CoolWallet S" },
  { value: "nash.io", label: "Nash" },
  { value: "coinomi.com", label: "Coinomi" },
  { value: "gridplus.io", label: "GridPlus" },
  { value: "tokenary.io", label: "Tokenary" },
  { value: "safepal.io", label: "SafePal" },
  { value: "infinitowallet.io", label: "Infinito" },
  { value: "wallet.io", label: "Wallet.io" },
  { value: "ownbit.io", label: "Ownbit" },
  { value: "easypocket.app", label: "EasyPocket" },
  { value: "mtpelerin.com", label: "Bridge Wallet" },
  { value: "viawallet.com", label: "ViaWallet" },
  { value: "bitkeep.com", label: "BitKeep" },
  { value: "unstoppable.money", label: "Unstoppable Wallet" },
  { value: "halodefi.org", label: "HaloDefi Wallet" },
  { value: "dokwallet.com", label: "Dok Wallet" },
  { value: "cellowallet.app", label: "Cello Wallet" },
  { value: "coinus.io", label: "CoinUs" },
  { value: "valoraapp.com", label: "Valora" },
  { value: "trusteeglobal.com", label: "Trustee Wallet" },
  { value: "guarda.com", label: "Gaurda Wallet" },
  { value: "Maiar.com", label: "Maiar Wallet" },
  { value: "jadewallet.io", label: "Jade Wallet" },
  { value: "plasmapay.com", label: "PlasmaPay" },
  { value: "o3.network", label: "O3Wallet" },
  { value: "me.hashkey.com", label: "HashKey Me" },
  { value: "rsk.co", label: "RWallet" },
  { value: "flarewallet.io", label: "Flare Wallet" },
  { value: "kyberswap.com", label: "KyberSwap" },
  { value: "atoken.com", label: "AToken Wallet" },
  { value: "tongue.fi", label: "Tongue Wallet" },
  { value: "xinfin.io", label: "XinFin XDC Network" },
  { value: "talken.io", label: "Talken Wallet" },
  { value: "keyring.app", label: "KEYRING PRO" },
  { value: "midasprotocol.io", label: "Midas Wallet" },
  { value: "oxygen.app", label: "Oxygen Wallet" },
  { value: "atomicwallet.io", label: "Atomic Wallet"},
  { value: "bestwallet.com", label: "Best Wallet" },
  { value: "bitget", label: "Bitget Wallet" },
  { value: "bybit.com", label: "Bybit Wallet" },
  { value: "Mycelium", label: "Mycelium" },
  { value: "token.im", label: "imToken" }
];